/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "AuthTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "supabase.index/project.Project"
      "user": string
    }
    "DatabaseMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FileUploadBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GoogleClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "SupabaseDatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}